// THIS FILE IS AUTOGENERATED, MODIFY weathers.json IN STEAD.

package {
public class WeatherPresets extends Object{
	public static const NIGHTGREEN:Object = {
		'saturation': 0.7,
		'darkness': 0.45,
		'sky': 0xFF005EA5,
		'haze': 0xFFB8F2BB,
		'sunTint': 0xDDDDFF,
		'fog': 0.4,
		'contrast': 0.0,
		'horizon': 0xFF002E80,
		'ambient': 0x2254FFAF,
		'timeOfDay': 0.85,
		'wind': 0.1,
		'darknessColor': 0x88263529
	}
	public static const NIGHTFOGGY:Object = {
		'saturation': 0.7,
		'darkness': 0.7,
		'sky': 0xFF25229d,
		'haze': 0xFFd5d9ff,
		'sunTint': 0xffd9c8,
		'fog': 1.0,
		'contrast': -0.1,
		'horizon': 0xFF6a6d55,
		'ambient': 0x7763709d,
		'timeOfDay': 0.8,
		'wind': 0.2,
		'darknessColor': 0x88111114
	}
	public static const NIGHTLONG:Object = {
		'saturation': 1.0,
		'darkness': 0.4,
		'sky': 0xFF7399c8,
		'sunTint': 0x162039,
		'haze': 0xFF000000,
		'fog': 0.0,
		'wind': 0.1,
		'horizon': 0xFF7399c8,
		'ambient': 0x55acc857,
		'timeOfDay': 0.9,
		'contrast': 0.3,
		'darknessColor': 0x88000000
	}
	public static const DAYCLEARCOLD:Object = {
		'saturation': 0.7,
		'darkness': 0.0,
		'sky': 0xFFC9E3EA,
		'haze': 0x33C9E3EA,
		'sunTint': 0xF7E9AA,
		'fog': 0.0,
		'contrast': 0.2,
		'horizon': 0xFFC9E3EA,
		'ambient': 0x33F7E0C3,
		'timeOfDay': 0.45,
		'wind': 0.5,
		'darknessColor': 0x88111114
	}
	public static const DAWNBLEAK:Object = {
		'saturation': 0.9,
		'darkness': 0.2,
		'sky': 0xFFC4AD99,
		'haze': 0xAAf3f1e8,
		'sunTint': 0xF9B340,
		'fog': 0.5,
		'contrast': 0.5,
		'horizon': 0xFFCECECE,
		'ambient': 0x22FF84DA,
		'timeOfDay': 0.31,
		'wind': 0.1,
		'darknessColor': 0x88111114
	}
	public static const DAYORANGESKY:Object = {
		'saturation': 0.7,
		'darkness': 0.1,
		'sky': 0xFFADA290,
		'haze': 0x445A432C,
		'sunTint': 0xF9F8E6,
		'fog': 0.3,
		'contrast': 0.2,
		'horizon': 0xFFDCAB4F,
		'ambient': 0x110E0B22,
		'timeOfDay': 0.4,
		'wind': 0.7,
		'darknessColor': 0x880E0B62
	}
	public static const DAYPASTEL:Object = {
		'saturation': 1.0,
		'darkness': 0.0,
		'sky': 0xFF3090F6,
		'sunTint': 0xF9F8E6,
		'haze': 0xDD657A8F,
		'fog': 0.0,
		'wind': 0.3,
		'horizon': 0xFFEEEE88,
		'ambient': 0x77886A00,
		'timeOfDay': 0.55,
		'contrast': 1.0,
		'darknessColor': 0x88000BBB
	}
	public static const DUSKPINK:Object = {
		'saturation': 0.9,
		'darkness': 0.0,
		'sky': 0xFF8C8CA6,
		'haze': 0xAAf3c1e8,
		'sunTint': 0xF9B340,
		'fog': 0.0,
		'contrast': 0.8,
		'horizon': 0xFFEDC99A,
		'ambient': 0x44F79A42,
		'timeOfDay': 0.65,
		'wind': 0.1,
		'darknessColor': 0x88111114
	}
	public static const DAWNCLEARORANGE:Object = {
		'saturation': 0.8,
		'darkness': 0.2,
		'sky': 0xFF97A7B4,
		'haze': 0x88FDB24C,
		'sunTint': 0xFAFDC9,
		'fog': 0.0,
		'contrast': 0.5,
		'horizon': 0xFFF9A04F,
		'ambient': 0x11FF0000,
		'timeOfDay': 0.28,
		'wind': 0.1,
		'darknessColor': 0x88111114
	}
	public static const EVENINGORANGE:Object = {
		'saturation': 0.8,
		'darkness': 0.1,
		'sky': 0xFF8BB8E8,
		'haze': 0xFFFF9068,
		'sunTint': 0xFFFF7038,
		'fog': 0.0,
		'contrast': 0.7,
		'horizon': 0xFFEDC99A,
		'ambient': 0x33DE5E37,
		'timeOfDay': 0.70,
		'wind': 0.1,
		'darknessColor': 0x88111114
	}
	public static const NIGHTSHINE:Object = {
		'saturation': 0.5,
		'darkness': 0.35,
		'sky': 0xFF000000,
		'sunTint': 0xF9F8E6,
		'haze': 0x00886AAA,
		'fog': 0.0,
		'wind': 0.2,
		'horizon': 0xFFAAAAFF,
		'ambient': 0x00000000,
		'timeOfDay': 0.9,
		'contrast': 4.0,
		'darknessColor': 0x88222255
	}
	public static const EVENINGFOGGY:Object = {
		'saturation': 0.7,
		'darkness': 0.3,
		'sky': 0xFFd56c47,
		'haze': 0xFFd5d9ff,
		'sunTint': 0xffd9c8,
		'fog': 1.0,
		'contrast': -0.1,
		'horizon': 0xFF6a6d55,
		'ambient': 0x440000FF,
		'timeOfDay': 0.7,
		'wind': 0.2,
		'darknessColor': 0x88111114
	}
	public static const NIGHTPURPLE:Object = {
		'saturation': 0.8,
		'darkness': 0.35,
		'sky': 0xFF57577D,
		'sunTint': 0xF9F8E6,
		'haze': 0x88886AAA,
		'fog': 0.0,
		'wind': 0.2,
		'horizon': 0xFF4D4658,
		'ambient': 0x55886AAA,
		'timeOfDay': 0.9,
		'contrast': 3.0,
		'darknessColor': 0x88990BBB
	}
	public static const EVENINGBLACK:Object = {
		'saturation': 0.7,
		'darkness': 0.3,
		'sky': 0xFF333333,
		'haze': 0xFFFF9090,
		'sunTint': 0xFFFF7038,
		'fog': 0.0,
		'contrast': 0.0,
		'horizon': 0xFFEDC99A,
		'ambient': 0x339f6b5c,
		'timeOfDay': 0.70,
		'wind': 0.1,
		'darknessColor': 0x88111114
	}
	public static const EVENINGMONOTONE:Object = {
		'saturation': 0.7,
		'darkness': 0.3,
		'sky': 0xFF333333,
		'haze': 0xFFFF9090,
		'sunTint': 0xAAAAAA,
		'fog': 0.0,
		'contrast': 0.0,
		'horizon': 0xFFEDEDED,
		'ambient': 0x33666666,
		'timeOfDay': 0.70,
		'wind': 0.1,
		'darknessColor': 0x88111114
	}
	public static const NIGHTCLEAR:Object = {
		'saturation': 0.8,
		'darkness': 0.4,
		'sky': 0xFF005EA5,
		'haze': 0x44434e87,
		'sunTint': 0xDDDDFF,
		'fog': 0.1,
		'contrast': -0.1,
		'horizon': 0xFF002E80,
		'ambient': 0x110000FF,
		'timeOfDay': 0.1,
		'wind': 0.3,
		'darknessColor': 0x88111114
	}
	public static const SUNNY:Object = {
		'saturation': 0.8,
		'darkness': 0.0,
		'sky': 0xFF98BEEC,
		'haze': 0xCCf3f1e8,
		'sunTint': 0xfff766,
		'fog': 0.0,
		'contrast': 0.8,
		'horizon': 0xFFC4DAF1,
		'ambient': 0x44FFBB7F,
		'timeOfDay': 0.6,
		'wind': 1.0,
		'darknessColor': 0x88111114
	}
	public static const DAYBLEAK:Object = {
		'saturation': 0.7,
		'darkness': 0.0,
		'sky': 0xFFA0C2E8,
		'haze': 0xFFf3f1e8,
		'sunTint': 0xF7E9AA,
		'fog': 1.0,
		'contrast': 0.0,
		'horizon': 0xFFA6C9ED,
		'ambient': 0x33F7E0C3,
		'timeOfDay': 0.45,
		'wind': 0.5,
		'darknessColor': 0x88111114
	}
	public static const NIGHTREDMOON:Object = {
		'saturation': 0.9,
		'darkness': 0.4,
		'sky': 0xFF142744,
		'haze': 0x665C5D9E,
		'sunTint': 0xC73800,
		'fog': 0.1,
		'contrast': 0.2,
		'horizon': 0xFFAD2E21,
		'ambient': 0x220E0B62,
		'timeOfDay': 0.1,
		'wind': 0.1,
		'darknessColor': 0x880E0B62
	}
	public static const DAYTEMP:Object = {
		'saturation': 0.0,
		'darkness': 0.2,
		'sky': 0xFF6a6d55,
		'haze': 0xFF999d7c,
		'sunTint': 0xffffff,
		'fog': 1.0,
		'contrast': -0.2,
		'horizon': 0xFF6a6d55,
		'ambient': 0xFFFF0000,
		'timeOfDay': 0.5,
		'wind': 0.2,
		'darknessColor': 0x88111114
	}
	public static const FOGGY:Object = {
		'saturation': 0.7,
		'darkness': 0.2,
		'sky': 0xFF6a6d55,
		'haze': 0xFF999d7c,
		'sunTint': 0xffffff,
		'fog': 1.0,
		'contrast': -0.2,
		'horizon': 0xFF6a6d55,
		'ambient': 0x330000FF,
		'timeOfDay': 0.25,
		'wind': 0.2,
		'darknessColor': 0x88111114
	}
	public static const DAWNBROWN:Object = {
		'saturation': 0.8,
		'darkness': 0.0,
		'sky': 0xFFC0AFBD,
		'sunTint': 0xF9F8E6,
		'haze': 0x99AAAAAA,
		'fog': 0.2,
		'wind': 0.2,
		'horizon': 0xFF94A9B6,
		'ambient': 0x55AD3200,
		'timeOfDay': 0.28,
		'contrast': 0.7,
		'darknessColor': 0x88222255
	}
	public static const DUSKFOGGY:Object = {
		'saturation': 0.6,
		'darkness': 0.25,
		'sky': 0xFFB29C8F,
		'sunTint': 0xF9F8E6,
		'haze': 0x00000000,
		'fog': 0.8,
		'wind': 0.4,
		'horizon': 0xFF3D6BCD,
		'ambient': 0x330E0B22,
		'timeOfDay': 0.75,
		'contrast': 0.1,
		'darknessColor': 0x880E0B62
	}
	public static const DAWNLIGHTPINK:Object = {
		'saturation': 0.8,
		'darkness': 0.1,
		'sky': 0xFF8C8CA6,
		'haze': 0xAAf3f1e8,
		'sunTint': 0xF9B340,
		'fog': 0.5,
		'contrast': 0.5,
		'horizon': 0xFFCF7968,
		'ambient': 0x22FF84DA,
		'timeOfDay': 0.28,
		'wind': 0.1,
		'darknessColor': 0x88111114
	}
	public static const NIGHTDARK:Object = {
		'saturation': 0.7,
		'darkness': 0.75,
		'sky': 0xFF002E33,
		'haze': 0xFF555555,
		'sunTint': 0x65a2cb,
		'fog': 0.0,
		'contrast': 0.4,
		'horizon': 0xFF002E80,
		'ambient': 0x4454AACF,
		'timeOfDay': 0.85,
		'wind': 0.1,
		'darknessColor': 0xFF263529
	}
	public static const DUSKWARM:Object = {
		'saturation': 0.9,
		'darkness': 0.0,
		'sky': 0xFF8BB8E8,
		'haze': 0x88f3f1e8,
		'sunTint': 0xF4EED0,
		'fog': 0.0,
		'contrast': 0.8,
		'horizon': 0xFFEDC99A,
		'ambient': 0x44F79A42,
		'timeOfDay': 0.65,
		'wind': 0.1,
		'darknessColor': 0x88111114
	}
	public static const DAWNBRIGHT:Object = {
		'saturation': 0.8,
		'darkness': 0.15,
		'sky': 0xFF57577D,
		'sunTint': 0xF9F8E6,
		'haze': 0x00886AAA,
		'fog': 0.0,
		'wind': 0.2,
		'horizon': 0xFFEEEE88,
		'ambient': 0xff886A00,
		'timeOfDay': 0.3,
		'contrast': 1.4,
		'darknessColor': 0x88000BBB
	}
	public static const DAWNGREY:Object = {
		'saturation': 0.5,
		'darkness': 0.2,
		'sky': 0xFFC4AD99,
		'haze': 0xAAf3f1e8,
		'sunTint': 0xF9B340,
		'fog': 0.5,
		'contrast': 0.5,
		'horizon': 0xFFCECECE,
		'ambient': 0x22FF84DA,
		'timeOfDay': 0.31,
		'wind': 0.1,
		'darknessColor': 0x88111114
	}
	public static const NIGHTSUPERDARK:Object = {
		'saturation': 0.7,
		'darkness': 0.7,
		'sky': 0xFF000000,
		'haze': 0xFFFFFFFF,
		'sunTint': 0x65a2cb,
		'fog': 0.0,
		'contrast': 0.4,
		'horizon': 0xFF002E80,
		'ambient': 0x4454AACF,
		'timeOfDay': 0.85,
		'wind': 0.1,
		'darknessColor': 0xFF263529
	}
	public static const DUSKCLEAR:Object = {
		'saturation': 0.9,
		'darkness': 0.2,
		'sky': 0xFF513744,
		'haze': 0xAAC9976D,
		'sunTint': 0xF9B340,
		'fog': 0.0,
		'contrast': 0.45,
		'horizon': 0xFFC69875,
		'ambient': 0x22360A00,
		'timeOfDay': 0.65,
		'wind': 0.1,
		'darknessColor': 0x88111114
	}
	public static const NIGHT:Object = {
		'saturation': 0.8,
		'darkness': 0.4,
		'sky': 0xFF005EA5,
		'haze': 0xFF333333,
		'sunTint': 0xDDDDFF,
		'fog': 0.2,
		'contrast': 0.5,
		'horizon': 0xFF002E80,
		'ambient': 0x110000FF,
		'timeOfDay': 0,
		'wind': 0.2,
		'darknessColor': 0x88111114
	}
	public static const DAWNTEMP:Object = {
		'saturation': 0.0,
		'darkness': 0.2,
		'sky': 0xFF6a6d55,
		'haze': 0xFF999d7c,
		'sunTint': 0xffffff,
		'fog': 1.0,
		'contrast': -0.2,
		'horizon': 0xFF6a6d55,
		'ambient': 0xFFFF0000,
		'timeOfDay': 0.25,
		'wind': 0.2,
		'darknessColor': 0x88111114
	}
	public static const DAYWINDYCLEAR:Object = {
		'saturation': 1.0,
		'darkness': 0.0,
		'sky': 0xFF64A3EA,
		'haze': 0x22f3f1e8,
		'sunTint': 0xF7E9AA,
		'fog': 0.0,
		'contrast': 1.0,
		'horizon': 0xFF86BAEF,
		'ambient': 0x33F99100,
		'timeOfDay': 0.45,
		'wind': 0.5,
		'darknessColor': 0x88111114
	}
	public static const DAWN:Object = {
		'saturation': 0.8,
		'darkness': 0.2,
		'sky': 0xFF8C8CA6,
		'haze': 0x66f3f1e8,
		'sunTint': 0xff6d40,
		'fog': 0.0,
		'contrast': 0.5,
		'horizon': 0xFFCF7968,
		'ambient': 0x11FF0000,
		'timeOfDay': 0.28,
		'wind': 0.1,
		'darknessColor': 0x88111114
	}
	public static const DAYSOFT:Object = {
		'saturation': 0.7,
		'darkness': 0.0,
		'sky': 0xFFA0C2E8,
		'haze': 0x22f3f1e8,
		'sunTint': 0xF7E9AA,
		'fog': 0.0,
		'contrast': 0.0,
		'horizon': 0xFFA6C9ED,
		'ambient': 0x33F7E0C3,
		'timeOfDay': 0.45,
		'wind': 0.1,
		'darknessColor': 0x88111114
	}
	public static const EVENING:Object = {
		'saturation': 0.8,
		'darkness': 0.1,
		'sky': 0xFFFF7F51,
		'haze': 0x99FF9068,
		'sunTint': 0xFFFF7038,
		'fog': 0.0,
		'contrast': 0.7,
		'horizon': 0xFFFFDF54,
		'ambient': 0x33DE5E37,
		'timeOfDay': 0.70,
		'wind': 0.1,
		'darknessColor': 0x88111114
	}
	public static const DAYMONOCHROME:Object = {
		'saturation': 0.15,
		'darkness': 0.0,
		'sky': 0xFF80A2C8,
		'haze': 0xFFf3f1e8,
		'sunTint': 0xF7E9AA,
		'fog': 1.0,
		'contrast': 0.4,
		'horizon': 0xFFA6C9ED,
		'ambient': 0x33F7E0C3,
		'timeOfDay': 0.45,
		'wind': 0.5,
		'darknessColor': 0x88111114
	}
	public static const DAWNREDMOON:Object = {
		'saturation': 0.9,
		'darkness': 0.2,
		'sky': 0xFF16549F,
		'haze': 0xbb5C5D9E,
		'sunTint': 0xE76833,
		'fog': 0.1,
		'contrast': 0.0,
		'horizon': 0xFFFF9286,
		'ambient': 0x110E0B22,
		'timeOfDay': 0.2,
		'wind': 0.1,
		'darknessColor': 0x880E0B62
	}
	public static const DUSKTAN:Object = {
		'saturation': 0.8,
		'darkness': 0.1,
		'sky': 0xFF52424C,
		'sunTint': 0xF9F8E6,
		'haze': 0x55C18F90,
		'fog': 0.0,
		'wind': 0.3,
		'horizon': 0xFFFFBA3B,
		'ambient': 0xFF886A00,
		'timeOfDay': 0.7,
		'contrast': 0.5,
		'darknessColor': 0x88330B33
	}
	public static const DUSKTEMP:Object = {
		'saturation': 0.0,
		'darkness': 0.2,
		'sky': 0xFF6a6d55,
		'haze': 0xFF999d7c,
		'sunTint': 0xffffff,
		'fog': 1.0,
		'contrast': -0.2,
		'horizon': 0xFF6a6d55,
		'ambient': 0xFFFF0000,
		'timeOfDay': 0.75,
		'wind': 0.2,
		'darknessColor': 0x88111114
	}
	public static const DUSKYELLOW:Object = {
		'saturation': 0.9,
		'darkness': 0.0,
		'sky': 0xFF8BB8E8,
		'haze': 0x88f3f1e8,
		'sunTint': 0xF4EED0,
		'fog': 0.0,
		'contrast': 0.8,
		'horizon': 0xFFEDC99A,
		'ambient': 0x44F79A42,
		'timeOfDay': 0.65,
		'wind': 0.1,
		'darknessColor': 0x88111114
	}
	public static const NIGHTTEMP:Object = {
		'saturation': 0.0,
		'darkness': 0.2,
		'sky': 0xFF6a6d55,
		'haze': 0xFF999d7c,
		'sunTint': 0xffffff,
		'fog': 1.0,
		'contrast': -0.2,
		'horizon': 0xFF6a6d55,
		'ambient': 0xFFFF0000,
		'timeOfDay': 0.0,
		'wind': 0.2,
		'darknessColor': 0x88111114
	}
	public static const DAYDUSTY:Object = {
		'saturation': 0.8,
		'darkness': 0.0,
		'sky': 0xFF5d9df5,
		'sunTint': 0xF9F8E6,
		'haze': 0x99AAAAAA,
		'fog': 0.2,
		'wind': 0.2,
		'horizon': 0xFF94A9B6,
		'ambient': 0x55f5db04,
		'timeOfDay': 0.4,
		'contrast': 0.2,
		'darknessColor': 0x88222255
	}
	public static const DUSKRED:Object = {
		'saturation': 0.8,
		'darkness': 0.2,
		'sky': 0xFFd06219,
		'sunTint': 0xf27612,
		'haze': 0x99AAAAAA,
		'fog': 0.2,
		'wind': 0.2,
		'horizon': 0xFFf2d407,
		'ambient': 0x55f5db04,
		'timeOfDay': 0.65,
		'contrast': 0.1,
		'darknessColor': 0x88000000
	}
}
}